#!/bin/bash
# Make Docker
#
# Purpose: This is a simple Bash script that builds, tags & pushes docker containers.


echo "Building $1"
cd $1
docker build -t $1 .
docker tag $1 merovex/$1:latest
docker push merovex/$1:latest
