version: 2
jobs:
  build:
    docker:
      # - image: debian:stretch
      - image: gioxa/pandoc-centos

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Fnord
          command: cd my-book && make pdf
