version: 2
publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

jobs:
  build:
    docker:
      - image: merovex/pandoc-book:latest
    steps:
      - checkout
      - run:
          name: Build Book
          command: |
            cd my-book
            make pdf docx epub html
            mkdir -p /tmp/builds
            cp build/*.* /tmp/builds

      - store_artifacts:
          path: /tmp/builds
  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
    requires:
      - build

workflows:
  version: 2
  build:
    jobs:
      - build
      - publish-github-release

          # filters:
          #   branches:
          #     ignore:
          #       - /server-dev-.*/
