version: 2
jobs:
  build:
    docker: [{image: "docker:17.12.0-ce-git"}]
    # docker:
    #   - image: debian:stretch

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Fnord
          command: cd my-book && make pdf 
