version: 2
jobs:
  build:
    docker:
      - image: merovex/pandoc-book:latest
    steps:
      - checkout
      - run:
          name: Build Book
          command: |
            VERSION=$(git describe --abbrev=0 --tags)
            cd my-book
            make book
            mkdir -p /tmp/builds
            cp -r build/* /tmp/builds

      - run:
          name: Deploy to Github
          command: |
            XVERSION=$(git describe --abbrev=0 --tags)
            VERSION=git describe --tags $(git rev-list --tags --max-count=1)
            echo ${VERSION}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/builds/
