version: 2
jobs:
  build:
    docker:
      - image: merovex/pandoc-book:latest

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Build Book
          command: |
            cd my-book
            make book
            mkdir -p /tmp/builds
            cp builds/*.* /tmp/builds
            
      - store_artifacts:
          path: /tmp/builds
