version: 2
jobs:
  build:
    docker:
      - image: merovex/pandoc-book:latest
    steps:
      - checkout
      - run:
          name: Build Book
          command: |
            VERSION=$(git describe --abbrev=0 --tags)
            cd my-book
            make pdf docx epub html
            mkdir -p /tmp/builds
            cp build/*.* /tmp/builds
            echo ${VERSION} > /tmp/builds/.version

      - store_artifacts:
          path: /tmp/builds
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./tmp/builds
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat .version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
